### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [lawre19/prj-rev-bwfs-dasmoto#8]
Grade: Needs improvement

Summary:
Lawrence congrats on finishing the Dasmoto project! You did an excellent job avoiding redundant CSS and remembering to use the alt attribute for all your images. 

Some things to consider going forward are avoiding inline CSS since it makes it harder to make future changes especially once your projects grow in size. As well to increase the readability of your HTML file consider adding comments and whitespace to separate your code visually. 

As a challenge try adding some hover effects to some sections of your project. Here is a [reference](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover) that you might find helpful if you decided to add some hover effects.

**Comment by lawre19** [comment]
So other than avoiding inline CSS what justifies such a bad grade? 
Why would I add hover effects? The assignment didn't ask for it, and I didn't know how to do them yet.
Am I being docked for not adding white space that I didn't want?
What is the difference between a suggestion and something that is worth docking grades?
The inline CSS and the file path, I get, but such a failing grade doesn't seem to match the two actual issues.

**Comment by jim-rosales** [comment]
![screen shot 2018-01-05 at 11 48 02 am](https://user-images.githubusercontent.com/28379087/34625649-6624f36a-f20e-11e7-9c49-678998605f61.png)

Adding hover effects are just a challenge for you to try to attempt for extra practice. It's up to you whether you want to do extra research and learn how to add them. The reference I gave you was to be used as a starting point. 

In regards to white space, I mentioned that because in industry adding whitespace is best practice because it makes a file easier to read and hence easier to maintain. As a web developer, there will be moments when you work in a team and making your file easier to read will allow your teammates to more easily understand what your code does in less time. 

You were docked heavily because using an absolute file path is a huge problem that will cause bugs as you continue. When I downloaded your project the screenshot above is how it is rendered. If you use relative file paths everything should work perfectly no matter the machine you use, which is necessary since most times sites live on a server and not on your machine. 

Also on line 18 you have another typo. You need to add a space between img and src. That will sometimes cause bugs and prevent your image from being rendered. Currently your have imgsrc which should be img src=""

**Comment by lawre19** [comment]
Thank you very much. Your response was extremely helpful and I appreciate it!
